"""initial schema

Revision ID: b03b8697f040
Revises: 
Create Date: 2026-04-25 15:12:32.018965

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03b8697f040'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('cabin', sa.String(length=1), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('only_direct', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notify_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=True),
    sa.Column('arrival_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('fare_brand', sa.String(length=30), nullable=False),
    sa.Column('fare_basis', sa.String(length=20), nullable=True),
    sa.Column('cabin', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('taxes_brl', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_captured_at'), 'price_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_price_snapshots_watch_captured', 'price_snapshots', ['watch_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_watch_id'), 'price_snapshots', ['watch_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['price_snapshots.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_watch_id'), 'alerts', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_watch_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_price_snapshots_watch_id'), table_name='price_snapshots')
    op.drop_index('ix_price_snapshots_watch_captured', table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_captured_at'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_table('watches')
    # ### end Alembic commands ###
